import { spawn } from "redux-saga/effects";
import { loginWatcher } from "./sagas/auth/loginSaga";
import forgotPasswordWatcher from "./sagas/auth/forgotPasswordSaga";
import resetPasswordWatcher from "./sagas/auth/resetPasswordSaga";
import dashboardWatcher from "./sagas/dashboard/dashboardSaga";
import liveBookingsWatcher from "./sagas/liveBookings/liveBookingSaga";
import riderManagementWatcher from "./sagas/riderManagement/riderManagementSaga";
import riderDetailWatcher from "./sagas/riderManagement/fetchRiderDetailSaga";
import approveRiderWatcher from "./sagas/riderManagement/approveRiderSaga";
import rejectRiderWatcher from "./sagas/riderManagement/rejectRiderSaga";
import suspendRiderWatcher from "./sagas/riderManagement/suspendRiderSaga";
import unsuspendRiderWatcher from "./sagas/riderManagement/unsuspendRiderSaga";
import onboardRiderWatcher from "./sagas/riderManagement/onboardRiderSaga";
import fetchReportsWatcher from "./sagas/reports/reportsSaga";
import fetchReportsByDateWatcher from "./sagas/reports/reportsByDateRangeSaga";
import fetchCompanySettingsWatcher from "./sagas/companyProfile/companyProfileSaga";
import updateCompanyProfileWatcher from "./sagas/companyProfile/updateCompanyProfileSaga";
import fetchPricingSettingsWatcher from "./sagas/pricing&Rate/pricingSettingsSaga";
import fetchZoneSettingsWatcher from "./sagas/serviceZones/zoneSettingsSaga";
import createServiceZoneWatcher from "./sagas/serviceZones/createServiceZoneSaga";
import deleteServiceZoneWatcher from "./sagas/serviceZones/deleteServiceZoneSaga";
import fetchZoneConfigWatcher from "./sagas/serviceZones/zoneConfigSaga";
import updateZoneConfigWatcher from "./sagas/serviceZones/updateZoneConfigSaga";
import fetchNotificationsWatcher from "./sagas/notifications/notificationsSaga";
import fetchAlertsCountWatcher from "./sagas/notifications/notificationsCountSaga";
import markAlertsReadWatcher from "./sagas/notifications/markAlertsReadSaga";
import fetchSupportCountWatcher from "./sagas/supportChat/supportCountSaga";
import updateRiderDocumentWatcher from "./sagas/riderManagement/updateRiderDocumentSaga";
import deleteRiderWatcher from "./sagas/riderManagement/deleteRiderSaga";
import fetchFleetWatcher from "./sagas/fleetTracking/fleetSaga";
import addBillingWatcher from "./sagas/billings/addBillingSaga";
import createZoneWatcher from "./sagas/riderManagement/createZoneWithRiderSaga";
import fetchSupportConversationsWatcher  from "./sagas/supportChat/fetchSupportConversationsSaga";
import fetchConversationMessagesWatcher  from "./sagas/supportChat/fetchConversationMessagesSaga";
import assignConversationWatcher         from "./sagas/supportChat/assignConversationSaga";
import resolveConversationWatcher        from "./sagas/supportChat/resolveConversationSaga";
import sendMessageWatcher               from "./sagas/supportChat/sendMessageSaga";
import uploadChatWatcher                from "./sagas/supportChat/uploadChatSaga";
import updatePricingWatcher from "./sagas/pricing&Rate/updatePricingSaga";
import toggleSurgeWatcher from "./sagas/pricing&Rate/toggleSurgeSaga";
import toggleSurgeRuleWatcher from "./sagas/pricing&Rate/toggleSurgeRuleSaga";
import updateSurgeRuleWatcher from "./sagas/pricing&Rate/updateSurgeRuleSaga";
import {
  fetchPlatformConfigWatcher,
  updatePlatformConfigWatcher,
} from "./sagas/platformConfig/platformConfigSaga";
import fetchBillingWatcher from "./sagas/billings/fetchBillingSaga";
import updateBillingWatcher from "./sagas/billings/updateBillingSaga";
import deleteBillingWatcher from "./sagas/billings/deleteBillingSaga";
import exportReportExcelWatcher from "./sagas/reports/exportReportPdfSaga";
import exportBillingExcelWatcher from "./sagas/billings/exportBillingExcelSaga";
import assignRiderZoneWatcher from "./sagas/serviceZones/assignRiderZoneSaga";
import updateZoneWatcher from "./sagas/serviceZones/updateZoneSaga";
import businessQuotesWatcher from "./sagas/websiteLeads/businessQuotesSaga";
import contactMessagesWatcher from "./sagas/websiteLeads/contactMessagesSaga";
import jobApplicationsWatcher from "./sagas/websiteLeads/jobApplicationsSaga";
import quoteRequestsWatcher from "./sagas/websiteLeads/quoteRequestsSaga";
import fetchQuoteRequestByIdWatcher from "./sagas/websiteLeads/fetchQuoteRequestByIdSaga";
import fetchBusinessQuoteByIdWatcher from "./sagas/websiteLeads/fetchBusinessQuoteByIdSaga";
import fetchContactMessageByIdWatcher from "./sagas/websiteLeads/fetchContactMessageByIdSaga";
import fetchJobApplicationByIdWatcher from "./sagas/websiteLeads/fetchJobApplicationByIdSaga";

export { SagaActions, SagaActionType } from "./sagas/sagaConstants";

export default function* rootSaga() {
  yield spawn(loginWatcher);
  yield spawn(forgotPasswordWatcher);
  yield spawn(resetPasswordWatcher);
  yield spawn(dashboardWatcher);
  yield spawn(liveBookingsWatcher);
  yield spawn(riderManagementWatcher);
  yield spawn(riderDetailWatcher);
  yield spawn(approveRiderWatcher);
  yield spawn(rejectRiderWatcher);
  yield spawn(suspendRiderWatcher);
  yield spawn(unsuspendRiderWatcher);
  yield spawn(onboardRiderWatcher);
  yield spawn(fetchReportsWatcher);
  yield spawn(fetchReportsByDateWatcher);
  yield spawn(fetchCompanySettingsWatcher);
  yield spawn(updateCompanyProfileWatcher);
  yield spawn(fetchPricingSettingsWatcher);
  yield spawn(fetchZoneSettingsWatcher);
  yield spawn(createServiceZoneWatcher);
  yield spawn(deleteServiceZoneWatcher);
  yield spawn(fetchZoneConfigWatcher);
  yield spawn(updateZoneConfigWatcher);
  yield spawn(fetchNotificationsWatcher);
  yield spawn(fetchAlertsCountWatcher);
  yield spawn(markAlertsReadWatcher);
  yield spawn(fetchSupportCountWatcher);
  yield spawn(updateRiderDocumentWatcher);
  yield spawn(deleteRiderWatcher);
  yield spawn(fetchFleetWatcher);
  yield spawn(addBillingWatcher);
  yield spawn(createZoneWatcher);
  yield spawn(fetchSupportConversationsWatcher);
  yield spawn(fetchConversationMessagesWatcher);
  yield spawn(assignConversationWatcher);
  yield spawn(resolveConversationWatcher);
  yield spawn(sendMessageWatcher);
  yield spawn(uploadChatWatcher);
  yield spawn(updatePricingWatcher);
  yield spawn(toggleSurgeWatcher);
  yield spawn(toggleSurgeRuleWatcher);
  yield spawn(updateSurgeRuleWatcher);
  yield spawn(fetchPlatformConfigWatcher);
  yield spawn(updatePlatformConfigWatcher);
  yield spawn(fetchBillingWatcher);
  yield spawn(updateBillingWatcher);
  yield spawn(deleteBillingWatcher);
  yield spawn(exportReportExcelWatcher);
  yield spawn(exportBillingExcelWatcher);
  yield spawn(assignRiderZoneWatcher);
  yield spawn(updateZoneWatcher);
  yield spawn(businessQuotesWatcher);
  yield spawn(contactMessagesWatcher);
  yield spawn(jobApplicationsWatcher);
  yield spawn(quoteRequestsWatcher);
  yield spawn(fetchQuoteRequestByIdWatcher);
  yield spawn(fetchBusinessQuoteByIdWatcher);
  yield spawn(fetchContactMessageByIdWatcher);
  yield spawn(fetchJobApplicationByIdWatcher);
}
